import '../timezone/timezone_model.dart';

class DefaultCities {
  // Pre-loaded curated favorites for instant, stunning first launch
  static const List<TimezoneItem> initialFavorites = [
    TimezoneItem(
      ianaId: 'Africa/Lagos',
      cityName: 'Lagos',
      countryName: 'Nigeria',
      countryCode: 'NG',
      flagEmoji: '🇳🇬',
      continent: 'Africa',
    ),
    TimezoneItem(
      ianaId: 'America/New_York',
      cityName: 'New York',
      countryName: 'United States',
      countryCode: 'US',
      flagEmoji: '🇺🇸',
      continent: 'America',
    ),
    TimezoneItem(
      ianaId: 'Europe/London',
      cityName: 'London',
      countryName: 'United Kingdom',
      countryCode: 'GB',
      flagEmoji: '🇬🇧',
      continent: 'Europe',
    ),
    TimezoneItem(
      ianaId: 'Asia/Tokyo',
      cityName: 'Tokyo',
      countryName: 'Japan',
      countryCode: 'JP',
      flagEmoji: '🇯🇵',
      continent: 'Asia',
    ),
    TimezoneItem(
      ianaId: 'Asia/Dubai',
      cityName: 'Dubai',
      countryName: 'United Arab Emirates',
      countryCode: 'AE',
      flagEmoji: '🇦🇪',
      continent: 'Asia',
    ),
    TimezoneItem(
      ianaId: 'Australia/Sydney',
      cityName: 'Sydney',
      countryName: 'Australia',
      countryCode: 'AU',
      flagEmoji: '🇦🇺',
      continent: 'Oceania',
    ),
  ];

  // Comprehensive world cities catalog for offline search and browsing
  static const List<TimezoneItem> allCities = [
    // Africa
    TimezoneItem(
      ianaId: 'Africa/Lagos',
      cityName: 'Lagos',
      countryName: 'Nigeria',
      countryCode: 'NG',
      flagEmoji: '🇳🇬',
      continent: 'Africa',
    ),
    TimezoneItem(
      ianaId: 'Africa/Cairo',
      cityName: 'Cairo',
      countryName: 'Egypt',
      countryCode: 'EG',
      flagEmoji: '🇪🇬',
      continent: 'Africa',
    ),
    TimezoneItem(
      ianaId: 'Africa/Johannesburg',
      cityName: 'Johannesburg',
      countryName: 'South Africa',
      countryCode: 'ZA',
      flagEmoji: '🇿🇦',
      continent: 'Africa',
    ),
    TimezoneItem(
      ianaId: 'Africa/Nairobi',
      cityName: 'Nairobi',
      countryName: 'Kenya',
      countryCode: 'KE',
      flagEmoji: '🇰🇪',
      continent: 'Africa',
    ),
    TimezoneItem(
      ianaId: 'Africa/Accra',
      cityName: 'Accra',
      countryName: 'Ghana',
      countryCode: 'GH',
      flagEmoji: '🇬🇭',
      continent: 'Africa',
    ),
    TimezoneItem(
      ianaId: 'Africa/Casablanca',
      cityName: 'Casablanca',
      countryName: 'Morocco',
      countryCode: 'MA',
      flagEmoji: '🇲🇦',
      continent: 'Africa',
    ),
    TimezoneItem(
      ianaId: 'Africa/Addis_Ababa',
      cityName: 'Addis Ababa',
      countryName: 'Ethiopia',
      countryCode: 'ET',
      flagEmoji: '🇪🇹',
      continent: 'Africa',
    ),

    // Americas
    TimezoneItem(
      ianaId: 'America/New_York',
      cityName: 'New York',
      countryName: 'United States',
      countryCode: 'US',
      flagEmoji: '🇺🇸',
      continent: 'America',
    ),
    TimezoneItem(
      ianaId: 'America/Los_Angeles',
      cityName: 'Los Angeles',
      countryName: 'United States',
      countryCode: 'US',
      flagEmoji: '🇺🇸',
      continent: 'America',
    ),
    TimezoneItem(
      ianaId: 'America/Chicago',
      cityName: 'Chicago',
      countryName: 'United States',
      countryCode: 'US',
      flagEmoji: '🇺🇸',
      continent: 'America',
    ),
    TimezoneItem(
      ianaId: 'America/Toronto',
      cityName: 'Toronto',
      countryName: 'Canada',
      countryCode: 'CA',
      flagEmoji: '🇨🇦',
      continent: 'America',
    ),
    TimezoneItem(
      ianaId: 'America/Vancouver',
      cityName: 'Vancouver',
      countryName: 'Canada',
      countryCode: 'CA',
      flagEmoji: '🇨🇦',
      continent: 'America',
    ),
    TimezoneItem(
      ianaId: 'America/Sao_Paulo',
      cityName: 'São Paulo',
      countryName: 'Brazil',
      countryCode: 'BR',
      flagEmoji: '🇧🇷',
      continent: 'America',
    ),
    TimezoneItem(
      ianaId: 'America/Buenos_Aires',
      cityName: 'Buenos Aires',
      countryName: 'Argentina',
      countryCode: 'AR',
      flagEmoji: '🇦🇷',
      continent: 'America',
    ),
    TimezoneItem(
      ianaId: 'America/Mexico_City',
      cityName: 'Mexico City',
      countryName: 'Mexico',
      countryCode: 'MX',
      flagEmoji: '🇲🇽',
      continent: 'America',
    ),
    TimezoneItem(
      ianaId: 'America/Bogota',
      cityName: 'Bogotá',
      countryName: 'Colombia',
      countryCode: 'CO',
      flagEmoji: '🇨🇴',
      continent: 'America',
    ),
    TimezoneItem(
      ianaId: 'America/Santiago',
      cityName: 'Santiago',
      countryName: 'Chile',
      countryCode: 'CL',
      flagEmoji: '🇨🇱',
      continent: 'America',
    ),

    // Europe
    TimezoneItem(
      ianaId: 'Europe/London',
      cityName: 'London',
      countryName: 'United Kingdom',
      countryCode: 'GB',
      flagEmoji: '🇬🇧',
      continent: 'Europe',
    ),
    TimezoneItem(
      ianaId: 'Europe/Paris',
      cityName: 'Paris',
      countryName: 'France',
      countryCode: 'FR',
      flagEmoji: '🇫🇷',
      continent: 'Europe',
    ),
    TimezoneItem(
      ianaId: 'Europe/Berlin',
      cityName: 'Berlin',
      countryName: 'Germany',
      countryCode: 'DE',
      flagEmoji: '🇩🇪',
      continent: 'Europe',
    ),
    TimezoneItem(
      ianaId: 'Europe/Rome',
      cityName: 'Rome',
      countryName: 'Italy',
      countryCode: 'IT',
      flagEmoji: '🇮🇹',
      continent: 'Europe',
    ),
    TimezoneItem(
      ianaId: 'Europe/Madrid',
      cityName: 'Madrid',
      countryName: 'Spain',
      countryCode: 'ES',
      flagEmoji: '🇪🇸',
      continent: 'Europe',
    ),
    TimezoneItem(
      ianaId: 'Europe/Amsterdam',
      cityName: 'Amsterdam',
      countryName: 'Netherlands',
      countryCode: 'NL',
      flagEmoji: '🇳🇱',
      continent: 'Europe',
    ),
    TimezoneItem(
      ianaId: 'Europe/Zurich',
      cityName: 'Zurich',
      countryName: 'Switzerland',
      countryCode: 'CH',
      flagEmoji: '🇨🇭',
      continent: 'Europe',
    ),
    TimezoneItem(
      ianaId: 'Europe/Stockholm',
      cityName: 'Stockholm',
      countryName: 'Sweden',
      countryCode: 'SE',
      flagEmoji: '🇸🇪',
      continent: 'Europe',
    ),
    TimezoneItem(
      ianaId: 'Europe/Moscow',
      cityName: 'Moscow',
      countryName: 'Russia',
      countryCode: 'RU',
      flagEmoji: '🇷🇺',
      continent: 'Europe',
    ),
    TimezoneItem(
      ianaId: 'Europe/Istanbul',
      cityName: 'Istanbul',
      countryName: 'Turkey',
      countryCode: 'TR',
      flagEmoji: '🇹🇷',
      continent: 'Europe',
    ),

    // Asia
    TimezoneItem(
      ianaId: 'Asia/Tokyo',
      cityName: 'Tokyo',
      countryName: 'Japan',
      countryCode: 'JP',
      flagEmoji: '🇯🇵',
      continent: 'Asia',
    ),
    TimezoneItem(
      ianaId: 'Asia/Singapore',
      cityName: 'Singapore',
      countryName: 'Singapore',
      countryCode: 'SG',
      flagEmoji: '🇸🇬',
      continent: 'Asia',
    ),
    TimezoneItem(
      ianaId: 'Asia/Dubai',
      cityName: 'Dubai',
      countryName: 'United Arab Emirates',
      countryCode: 'AE',
      flagEmoji: '🇦🇪',
      continent: 'Asia',
    ),
    TimezoneItem(
      ianaId: 'Asia/Hong_Kong',
      cityName: 'Hong Kong',
      countryName: 'Hong Kong',
      countryCode: 'HK',
      flagEmoji: '🇭🇰',
      continent: 'Asia',
    ),
    TimezoneItem(
      ianaId: 'Asia/Shanghai',
      cityName: 'Shanghai / Beijing',
      countryName: 'China',
      countryCode: 'CN',
      flagEmoji: '🇨🇳',
      continent: 'Asia',
    ),
    TimezoneItem(
      ianaId: 'Asia/Seoul',
      cityName: 'Seoul',
      countryName: 'South Korea',
      countryCode: 'KR',
      flagEmoji: '🇰🇷',
      continent: 'Asia',
    ),
    TimezoneItem(
      ianaId: 'Asia/Kolkata',
      cityName: 'New Delhi / Mumbai',
      countryName: 'India',
      countryCode: 'IN',
      flagEmoji: '🇮🇳',
      continent: 'Asia',
    ),
    TimezoneItem(
      ianaId: 'Asia/Bangkok',
      cityName: 'Bangkok',
      countryName: 'Thailand',
      countryCode: 'TH',
      flagEmoji: '🇹🇭',
      continent: 'Asia',
    ),
    TimezoneItem(
      ianaId: 'Asia/Jakarta',
      cityName: 'Jakarta',
      countryName: 'Indonesia',
      countryCode: 'ID',
      flagEmoji: '🇮🇩',
      continent: 'Asia',
    ),
    TimezoneItem(
      ianaId: 'Asia/Riyadh',
      cityName: 'Riyadh',
      countryName: 'Saudi Arabia',
      countryCode: 'SA',
      flagEmoji: '🇸🇦',
      continent: 'Asia',
    ),

    // Oceania
    TimezoneItem(
      ianaId: 'Australia/Sydney',
      cityName: 'Sydney',
      countryName: 'Australia',
      countryCode: 'AU',
      flagEmoji: '🇦🇺',
      continent: 'Oceania',
    ),
    TimezoneItem(
      ianaId: 'Australia/Melbourne',
      cityName: 'Melbourne',
      countryName: 'Australia',
      countryCode: 'AU',
      flagEmoji: '🇦🇺',
      continent: 'Oceania',
    ),
    TimezoneItem(
      ianaId: 'Pacific/Auckland',
      cityName: 'Auckland',
      countryName: 'New Zealand',
      countryCode: 'NZ',
      flagEmoji: '🇳🇿',
      continent: 'Oceania',
    ),
    TimezoneItem(
      ianaId: 'Pacific/Honolulu',
      cityName: 'Honolulu (Hawaii)',
      countryName: 'United States',
      countryCode: 'US',
      flagEmoji: '🇺🇸',
      continent: 'Oceania',
    ),
  ];
}
